@startuml

skinparam defaultFontName Arial
skinparam defaultFontSize 42
skinparam classFontSize 52

skinparam rectangle {
    BackgroundColor Snow
    BorderColor Black
    Shadowing true
}

skinparam class {
    BackgroundColor<<factory>> YellowGreen
    BackgroundColor<<node>> PaleGreen
    BackgroundColor<<parser>> Orange
    BackgroundColor<<engine>> LightBlue
    BackgroundColor<<registry>> LightYellow
}

rectangle "FusionBinary Parsing" as Parsing <<parser>> {
    class FusionBinaryParser
    class FusionBinaryReader
}

rectangle "Node Factories" as Factories <<factory>> {
    class TextNodeFactory
    class BoxNodeFactory
    class LayoutNodeFactory
    class ViewNodeFactory
    class AtomNodeFactory
}

rectangle "Node Structure" as Nodes <<node>> {
    class TextNode
    class BoxNode
    class LayoutNode
    class ViewNode
    class AtomNode
}

rectangle "Fusion Engine" as Engine <<engine>> {
    class FusionEngine
    class MoleculeDownloader
    class FusionController
    class Rendering
}

rectangle "Native" as Native <<native>> {
    class FusionAtomRegistry
    class Layout
    class Text
    class Box
}

class FusionContext

' Connections
FusionBinaryParser -left-> FusionBinaryReader : "bytes"
FusionBinaryParser -down-> TextNodeFactory : "produces"
FusionBinaryParser --> BoxNodeFactory : "produces"
BoxNodeFactory -down-> LayoutNodeFactory : "implements"
LayoutNodeFactory --> ViewNodeFactory : "implements"
TextNodeFactory --> ViewNodeFactory : "implements"
ViewNodeFactory --> AtomNodeFactory : "implements"
ViewNodeFactory -left-> ViewNode : "builds"
BoxNode --> LayoutNode : "implements"
LayoutNode --> ViewNode : "implements"
TextNode -left-> ViewNode : "implements"
ViewNode --> FusionContext : "import"
ViewNode -up-> AtomNode : "implements"

FusionEngine -right-> FusionBinaryParser : "import"
FusionEngine --> MoleculeDownloader : "import"
MoleculeDownloader --> FusionController : "produces \n*.fusion"
FusionController -down-> Rendering : "render()         "
Rendering -down-> FusionAtomRegistry : "import"
FusionAtomRegistry --> Layout : "maps"
FusionAtomRegistry -right-> Text : "maps"
Box -up-> Layout : "implements"

@enduml
