@startuml

actor Разработчик
participant "Fusion DSL" as DSL
participant "Fusion Движок" as Engine
participant Бекенд
participant "Веб Админка" as Admin
participant Клиент

Разработчик -> DSL : Пишет код
DSL -> Engine : Передает DSL код
Engine -> Engine : Строит вычисляемое дерево
Engine -> Engine : Валидация
Engine -> Engine : Конвертация в бинарный формат
Engine -> Бекенд : Отправляет бинарное представление
Бекенд -> Admin : Отображает данные для настройки шаблонов
Admin -> Бекенд : Настраивает шаблоны
Бекенд -> Клиент : Отправляет шаблон
Клиент -> Клиент : Скачивает шаблон
Клиент -> Клиент : Вычисляет ноды дерева
Клиент -> Клиент : Строит UI из нативных компонентов

@enduml